# VK Video ?? Android 11
vkvideo.version=11
vkvideo.device=emulator-5554
vkvideo.path=apps/vk_video.apk
vkvideo.package=com.vk.vkvideo
vkvideo.activity=com.vk.video.screens.main.MainActivity

# Alchemy ?? Android 16
alchemy.version=16
alchemy.device=emulator-5556
alchemy.path=apps/alchemy.apk
alchemy.package=com.ilyin.alchemy
alchemy.activity=com.ilyin.app_google_core.GoogleAppActivity